### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by fvieir** [cdsalema/PersonalSite_template#1]
Fala Conrado

Conforme deixado o Feedback e orientações no Discord, segue minhas solicitação para entrega do deploy.

Para deploy você pode usar o netlify ou github, mas sinta-se livre para usar outras plataformas.

Qualquer duvida é so chamar.

Forte abraço.

**Comment by cdsalema** [comment]
Vou fazer sim.  obg.

**Comment by cdsalema** [comment]
https://conradosalema.netlify.app/
