### ISSUE TITLE
Estrtutura das pasta

### ISSUE THREAD

**Issue by fvieir** [cdsalema/PersonalSite_template#2]
Olá Conrado.

Conforme deixado o Feedback e orientações no Discord, segue minha solicitação para organizar a estrtutura das pastas.
Segue uma ideia de como estruturar as pastas.

![image](https://user-images.githubusercontent.com/65264206/196414235-35e7d046-da1a-42d8-8206-bbc0b86641af.png)

Qualquer duvida é so chamar.

**Comment by cdsalema** [comment]
Opa, Fabricio! obrigado pelo toque. acabei de fazer a alteração das pastas.

**Comment by cdsalema** [comment]
`
![image](https://user-images.githubusercontent.com/56089674/219046189-3cd71c4f-a282-4679-bfef-67a704e2eb85.png)
`

**Comment by cdsalema** [comment]
![image](https://user-images.githubusercontent.com/56089674/219046320-e708f39a-f667-4aee-91a8-8d7ed7903e0c.png)
